/// CAH3 subjects (the fact table's subject grain), with CAH1 and CAH2 parents flattened onto each row for the CAH1 > CAH2 > CAH3 hierarchy.
table dim_cah
	lineageTag: 993aea75-35de-4c24-afe3-eb89a1776c91

	/// CAH3 subject code. Primary key.
	column cah_code
		dataType: string
		isKey
		lineageTag: 1ab841da-dd5f-4d3f-89b3-74bb2789d078
		summarizeBy: none
		sourceColumn: cah_code

	/// CAH3 subject name.
	column cah_name
		dataType: string
		lineageTag: 405b76dc-da52-47f6-9e32-a71adf23b4f1
		summarizeBy: none
		sourceColumn: cah_name

	/// CAH1 parent code.
	column cah1_code
		dataType: string
		lineageTag: 893e9872-e52f-4fb5-9d50-e36481452226
		summarizeBy: none
		sourceColumn: cah1_code

	/// CAH2 parent code.
	column cah2_code
		dataType: string
		lineageTag: 7c36437b-4506-4b7f-ae0e-e79b948aef96
		summarizeBy: none
		sourceColumn: cah2_code

	/// CAH1 parent name.
	column cah1_name
		dataType: string
		lineageTag: ff792268-b776-433e-82d7-33bdc950c297
		summarizeBy: none
		sourceColumn: cah1_name

	/// CAH2 parent name.
	column cah2_name
		dataType: string
		lineageTag: b86cd99a-5b47-48c1-8f85-4369f5d276d9
		summarizeBy: none
		sourceColumn: cah2_name

	/// CAH1 > CAH2 > CAH3 subject drill path. Every fact row is at CAH3; higher levels are roll-ups of published CAH3 results only (small unpublished groups are missing).
	hierarchy 'Subject hierarchy'
		lineageTag: 13ecc177-1775-4a15-a7bd-db9fc2598d42

		level CAH1
			lineageTag: 8a8f2fdf-ef99-448b-8fd7-b413a4a3248c
			column: cah1_name

		level CAH2
			lineageTag: e549b8b8-2bf8-4e17-bdbd-db8edfffb46b
			column: cah2_name

		level Subject
			lineageTag: 067b63b1-9c49-4ea2-af4a-9087194161d2
			column: cah_name

	partition dim_cah = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "dim_cah.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"cah_code", type text}, {"cah_name", type text}, {"cah1_code", type text}, {"cah1_name", type text}, {"cah2_code", type text}, {"cah2_name", type text}})
				in
				    Typed

