/// NSS published results, Taught population, at the most detailed published grain: ukprn x mode_of_study x level_of_study x CAH3 subject x question_no. Totals (All subjects, CAH1, CAH2, All undergraduates) are not included, so rows are disjoint. Never sum or average percentage columns; pool option counts instead. HC questions excluded in Power Query.
table fact_teach
	lineageTag: 365d84be-9296-4382-a150-c6deb4b7653f

	/// DERIVED, NOT PUBLISHED. Positivity pooled from option counts across all rows in context: (option1 + option2) / (option1..option5); option5 is only used by Q28. Rows are disjoint CAH3 x level x mode x provider groups, so pooling across providers, modes, levels and subjects is valid. Matches the published figure within 0.1 pp on about 95% of single rows (mismatches are rows with fractional option counts).
	measure 'Positivity %' =
			VAR _positive = SUM ( fact_teach[option1] ) + SUM ( fact_teach[option2] )
			VAR _answered =
			    SUM ( fact_teach[option1] ) + SUM ( fact_teach[option2] ) + SUM ( fact_teach[option3] )
			        + SUM ( fact_teach[option4] ) + SUM ( fact_teach[option5] )
			RETURN
			    DIVIDE ( _positive, _answered )
		formatString: 0.0%
		displayFolder: Core
		lineageTag: 7ef2dfd9-1bda-4902-a035-2af5a48bd012

	/// Published survey response headcount (whole students, all questions), counted once per provider x mode x level x subject group rather than once per question. Summed over subjects, a student on a multi-subject course counts once per subject.
	measure 'Response headcount' =
			VAR _groups =
			    SUMMARIZE ( fact_teach, fact_teach[ukprn], fact_teach[mode_of_study], fact_teach[level_of_study], fact_teach[cah_code] )
			RETURN
			    SUMX ( _groups, CALCULATE ( MAX ( fact_teach[pub_response_headcount] ) ) )
		formatString: #,0
		displayFolder: Core
		lineageTag: b9acbc48-227b-42b3-b7a9-ffc8f023fe8f

	/// Survey response rate. For one provider x mode x level x subject group it equals the published pub_resprate. For several groups it is pooled (derived): total response headcount / total survey population, where each group's survey population in whole students is headcount / published rate. Groups with a 0% rate are skipped.
	measure 'Response rate %' =
			VAR _groups =
			    ADDCOLUMNS (
			        SUMMARIZE ( fact_teach, fact_teach[ukprn], fact_teach[mode_of_study], fact_teach[level_of_study], fact_teach[cah_code] ),
			        "@headcount", CALCULATE ( MAX ( fact_teach[pub_response_headcount] ) ),
			        "@rate", CALCULATE ( MAX ( fact_teach[pub_resprate] ) )
			    )
			VAR _valid = FILTER ( _groups, [@rate] > 0 )
			VAR _respondents = SUMX ( _valid, [@headcount] )
			VAR _surveyed = SUMX ( _valid, [@headcount] * 100 / [@rate] )
			RETURN
			    DIVIDE ( _respondents, _surveyed )
		formatString: 0.0%
		displayFolder: Core
		lineageTag: 6c221da0-be9b-439f-a43d-1ae5a1dd69e0

	/// Number of published results (fact rows) in context above benchmark at the selected Confidence threshold. With one provider, mode, level and subject selected this is a count of questions; with more selected it counts every provider x mode x level x subject x question result.
	measure 'Questions above benchmark' =
			VAR _t = [Confidence threshold Value]
			RETURN
			    IF (
			        NOT ISEMPTY ( fact_teach ),
			        CALCULATE ( COUNTROWS ( fact_teach ), fact_teach[materially_above_bench] >= _t ) + 0
			    )
		formatString: #,0
		displayFolder: Significance
		lineageTag: daff4321-35c3-4eb5-89cb-3cdd5b9c520a

	/// Number of published results (fact rows) in context below benchmark at the selected Confidence threshold. With one provider, mode, level and subject selected this is a count of questions; with more selected it counts every result.
	measure 'Questions below benchmark' =
			VAR _t = [Confidence threshold Value]
			RETURN
			    IF (
			        NOT ISEMPTY ( fact_teach ),
			        CALCULATE ( COUNTROWS ( fact_teach ), fact_teach[materially_below_bench] >= _t ) + 0
			    )
		formatString: #,0
		displayFolder: Significance
		lineageTag: 1db1b03f-9cbc-41a0-98eb-b82387c1252c

	/// Estimates how many more students would need to respond positively to reach benchmark: number_population x -MIN(difference, 0) / 100, calculated per result row and summed. When rolled up over several questions one student can count on several questions.
	measure 'Students below benchmark (est.)' = SUMX ( fact_teach, fact_teach[number_population] * MAX ( -fact_teach[difference], 0 ) / 100 )
		formatString: #,0
		displayFolder: Priority
		lineageTag: 575f834e-db1c-4571-8a1d-ccc8c0b01575

	/// UK Provider Reference Number. FK to dim_provider.
	column ukprn
		dataType: string
		isHidden
		lineageTag: e2fa53e9-6388-426e-b905-9418159d06b9
		summarizeBy: none
		sourceColumn: ukprn

	/// Provider name (denormalised; use dim_provider).
	column provider_name
		dataType: string
		isHidden
		lineageTag: 0e4f5b57-f92b-43dd-9a28-fe28ada842af
		summarizeBy: none
		sourceColumn: provider_name

	/// FK to dim_mode.
	column mode_of_study
		dataType: string
		isHidden
		lineageTag: 5da21463-1ee5-48e3-a172-10dc96e36a5b
		summarizeBy: none
		sourceColumn: mode_of_study

	/// FK to dim_level.
	column level_of_study
		dataType: string
		isHidden
		lineageTag: c4cc4533-2154-4f4f-a250-8f93e4269c85
		summarizeBy: none
		sourceColumn: level_of_study

	/// Always CAH3 (denormalised; not needed in the report).
	column subject_level
		dataType: string
		isHidden
		lineageTag: 7cad359d-a557-4380-a75c-10d3752f1121
		summarizeBy: none
		sourceColumn: subject_level

	/// Subject code; ALL for All subjects. FK to dim_cah.
	column cah_code
		dataType: string
		isHidden
		lineageTag: a45eea8b-3a51-4403-a298-fcf2a7889c74
		summarizeBy: none
		sourceColumn: cah_code

	/// Subject name (denormalised; use dim_cah).
	column cah_name
		dataType: string
		isHidden
		lineageTag: 6e830b60-73b0-4d00-825f-29558878fa13
		summarizeBy: none
		sourceColumn: cah_name

	/// Theme number (denormalised; use dim_theme_question).
	column theme_no
		dataType: int64
		isHidden
		lineageTag: 81f59407-e989-4617-8244-81d00df64a11
		summarizeBy: none
		sourceColumn: theme_no

	/// Question code. FK to dim_theme_question.
	column question_no
		dataType: string
		isHidden
		lineageTag: 00dc865c-bd62-4089-8c3a-26cf104e32e3
		summarizeBy: none
		sourceColumn: question_no

	/// Respondents who answered the question. Can be fractional (multi-subject students are split).
	column number_responses
		dataType: double
		lineageTag: add90bfd-cf3d-4f74-8f45-2e95e68d4ea7
		summarizeBy: none
		sourceColumn: number_responses

	/// Students surveyed in the group (target population).
	column number_population
		dataType: double
		lineageTag: 2bd25caf-c5ef-4fd0-848c-697dfeb204bd
		summarizeBy: none
		sourceColumn: number_population

	/// Respondents choosing option 1 (most positive).
	column option1
		dataType: double
		lineageTag: a4ababf4-aaca-4041-802e-c8e2be31ff72
		summarizeBy: none
		sourceColumn: option1

	/// Respondents choosing option 2.
	column option2
		dataType: double
		lineageTag: 24001652-f201-4842-b5d8-27a535a37703
		summarizeBy: none
		sourceColumn: option2

	/// Respondents choosing option 3.
	column option3
		dataType: double
		lineageTag: 5f57c0b4-d7eb-48e2-9c84-fabe0869e15a
		summarizeBy: none
		sourceColumn: option3

	/// Respondents choosing option 4.
	column option4
		dataType: double
		lineageTag: 03143262-2c98-4238-962f-ce222a69a1c8
		summarizeBy: none
		sourceColumn: option4

	/// Respondents choosing option 5 (5-point question Q28 only).
	column option5
		dataType: double
		lineageTag: d169c3e6-8958-415f-b455-6d8551efc796
		summarizeBy: none
		sourceColumn: option5

	/// 'This does not apply to me' responses; excluded from number_responses.
	column not_applicable
		dataType: double
		lineageTag: 10ac0317-f802-4823-b255-f3927ccb7d18
		summarizeBy: none
		sourceColumn: not_applicable

	/// Published positivity, % on a 0-100 scale. Never sum or average.
	column positivity_measure
		dataType: double
		formatString: 0.0
		lineageTag: 52fddb6c-45ee-418f-b40f-60fc5a19cb1a
		summarizeBy: none
		sourceColumn: positivity_measure

	/// Standard deviation of the positivity measure.
	column standard_deviation
		dataType: double
		lineageTag: dc6c2880-241d-4db3-ba93-1095970ddd9c
		summarizeBy: none
		sourceColumn: standard_deviation

	/// Benchmark positivity, % on a 0-100 scale. Never sum or average.
	column benchmark
		dataType: double
		formatString: 0.0
		lineageTag: 6158c9f5-6611-44e5-ac58-0043d975d6ac
		summarizeBy: none
		sourceColumn: benchmark

	/// positivity_measure - benchmark, in percentage points.
	column difference
		dataType: double
		formatString: +0.0;-0.0;0.0
		lineageTag: 3195f866-7c68-484b-84f8-54e1fce53c88
		summarizeBy: none
		sourceColumn: difference

	/// Provider's own share of its benchmark population, % 0-100. Above 50 the comparison is weak.
	column contr_benchmark
		dataType: double
		lineageTag: 05aefd8b-5bde-44a8-9c9c-1fb7fcafaf74
		summarizeBy: none
		sourceColumn: contr_benchmark

	/// Confidence (%) that the true difference is more than 2.5 pp below benchmark.
	column materially_below_bench
		dataType: double
		lineageTag: deb99ee8-a488-45ff-83b1-d66f2bfbcb65
		summarizeBy: none
		sourceColumn: materially_below_bench

	/// Confidence (%) that the true difference is within +/-2.5 pp of benchmark.
	column inline_with_bench
		dataType: double
		lineageTag: dfcf5ef3-ad6c-430d-bae3-f976508ae744
		summarizeBy: none
		sourceColumn: inline_with_bench

	/// Confidence (%) that the true difference is more than 2.5 pp above benchmark.
	column materially_above_bench
		dataType: double
		lineageTag: 4fcacafd-0040-473c-8cf9-cb83a1056ccf
		summarizeBy: none
		sourceColumn: materially_above_bench

	/// Lower 95% CI of difference, pp.
	column difference_lowerci95
		dataType: double
		formatString: +0.0;-0.0;0.0
		lineageTag: 009c9c45-f0ef-4159-a692-f65d1fdeccfb
		summarizeBy: none
		sourceColumn: difference_lowerci95

	/// Upper 95% CI of difference, pp.
	column difference_upperci95
		dataType: double
		formatString: +0.0;-0.0;0.0
		lineageTag: df99860b-a0af-4a0c-b6fb-758b2465a2d6
		summarizeBy: none
		sourceColumn: difference_upperci95

	/// Lower 95% CI of positivity, % 0-100.
	column indicator_lowerci95
		dataType: double
		lineageTag: 12f1a434-d3d6-4c90-a72d-9a9387021a0c
		summarizeBy: none
		sourceColumn: indicator_lowerci95

	/// Upper 95% CI of positivity, % 0-100.
	column indicator_upperci95
		dataType: double
		lineageTag: 69020dd4-abbe-4042-b3d3-6b030435a9fb
		summarizeBy: none
		sourceColumn: indicator_upperci95

	/// Published survey response headcount for the group (all questions).
	column pub_response_headcount
		dataType: double
		lineageTag: bc3c1823-9d1a-439b-9c60-1a133a8e6879
		summarizeBy: none
		sourceColumn: pub_response_headcount

	/// Published response rate for the group, % 0-100.
	column pub_resprate
		dataType: double
		formatString: 0.0
		lineageTag: b038e34b-b813-4a36-964d-a37df9266f31
		summarizeBy: none
		sourceColumn: pub_resprate

	/// Materially above / below / Broadly in line with benchmark (90% confidence). Blank where materially_* is blank.
	column benchmark_category
		dataType: string
		lineageTag: 77f5924c-3d52-4645-910e-fc4f95ee46f2
		summarizeBy: none
		sourceColumn: benchmark_category

	/// CAH1 parent code of the subject (denormalised; use dim_cah).
	column cah1_code
		dataType: string
		isHidden
		lineageTag: 9f8625fe-e853-4d8e-9742-ea9b81f99f5a
		summarizeBy: none
		sourceColumn: cah1_code

	/// CAH1 parent name (denormalised; use dim_cah).
	column cah1_name
		dataType: string
		isHidden
		lineageTag: 543cd62d-4038-41f1-8b5f-00946e08a070
		summarizeBy: none
		sourceColumn: cah1_name

	/// CAH2 parent code of the subject (denormalised; use dim_cah).
	column cah2_code
		dataType: string
		isHidden
		lineageTag: 6a0c235f-0786-42fd-b199-72639c081bdf
		summarizeBy: none
		sourceColumn: cah2_code

	/// CAH2 parent name (denormalised; use dim_cah).
	column cah2_name
		dataType: string
		isHidden
		lineageTag: aabbc810-6a55-4563-800f-3649c723c0be
		summarizeBy: none
		sourceColumn: cah2_name

	column benchmark_pct = fact_teach[benchmark] / 100
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 6c6d2ff2-2943-478d-b5e9-8bf0da017809
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition fact_teach = m
		mode: import
		source =
				let
				    Source = Parquet.Document(File.Contents(DataFolder & "fact_teach.parquet")),
				    NoHC = Table.SelectRows(Source, each not Text.StartsWith([question_no], "HC")),
				    Typed = Table.TransformColumnTypes(NoHC, {
				        {"ukprn", type text}, {"provider_name", type text}, {"mode_of_study", type text}, {"level_of_study", type text},
				        {"subject_level", type text}, {"cah1_code", type text}, {"cah1_name", type text}, {"cah2_code", type text}, {"cah2_name", type text},
				        {"cah_code", type text}, {"cah_name", type text}, {"theme_no", Int64.Type}, {"question_no", type text},
				        {"number_responses", type number}, {"number_population", type number},
				        {"option1", type number}, {"option2", type number}, {"option3", type number}, {"option4", type number}, {"option5", type number}, {"not_applicable", type number},
				        {"positivity_measure", type number}, {"standard_deviation", type number}, {"benchmark", type number}, {"difference", type number}, {"contr_benchmark", type number},
				        {"materially_below_bench", type number}, {"inline_with_bench", type number}, {"materially_above_bench", type number},
				        {"difference_lowerci95", type number}, {"difference_upperci95", type number}, {"indicator_lowerci95", type number}, {"indicator_upperci95", type number},
				        {"pub_response_headcount", type number}, {"pub_resprate", type number}, {"benchmark_category", type text}})
				in
				    Typed

